{
 "title": "DevOps",
 "time": { "from": "2022-08-03T00:00:00.000Z", "to": "2022-08-16T00:00:00.000Z" },
 "panels": [
  {
   "title": "Number of commits by individual on a single day",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date(committed_date) AS time,\n  commiter_name AS metric,\n  count(commiter_name) AS value\nFROM metrics WHERE date(committed_date) = (SELECT date(committed_date) from metrics ORDER BY date(committed_date) DESC LIMIT 1)\nGROUP BY commiter_name, DATE(committed_date)\nORDER BY date(committed_date)"
    }
   ]
  },
  {
   "title": "Number of Commits by Individual",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date(committed_date) AS time,\n  commiter_name AS metric,\n  count(commiter_name) AS value\nFROM metrics\nGROUP BY commiter_name, DATE(committed_date)\nORDER BY date(committed_date) ASC"
    }
   ]
  },
  {
   "title": "Number of commits by team",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date(committed_date) AS time,\n  count(commiter_name) AS \"Commit\"\nFROM metrics\nGROUP BY DATE(committed_date)\nORDER BY date(committed_date) ASC"
    }
   ]
  },
  {
   "title": "NLOC (Number of lines of code)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  committed_date AS time,\n  nloc AS \"NLOC\"\nFROM metrics\nORDER BY committed_date ASC"
    }
   ]
  },
  {
   "title": "NLOC Added",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  committed_date AS time,\n  nloc_added AS \"NLOC Added\"\nFROM metrics\nORDER BY committed_date ASC"
    }
   ]
  },
  {
   "title": "NLOC Deleted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  committed_date AS time,\n  nloc_deleted AS \"NLOC Deleted\"\nFROM metrics\nORDER BY committed_date ASC"
    }
   ]
  },
  {
   "title": "Change Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  committed_date AS time,\n  change_rate AS \"Change Rate\"\nFROM metrics\nORDER BY committed_date ASC"
    }
   ]
  },
  {
   "title": "Production Deployment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE(committed_date) AS time,\n  COUNT(production_deployment) AS \"Production Deployment\"\nFROM metrics\nGROUP BY DATE(committed_date)\nORDER BY DATE(committed_date) ASC"
    }
   ]
  },
  {
   "title": "Cyclomatic Complexity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  committed_date AS time,\n  cyclomatic_complexity AS \"Cyclomatic Complexity\"\nFROM metrics\nORDER BY committed_date ASC"
    }
   ]
  }
 ]
}